### ISSUE TITLE
Question About Installing

### ISSUE THREAD

**Issue by epcdrs** [sloan58/twilio-autodialer#1]
Hi sloan 58,

This looks like an awesome application, thanks for creating it!

I am new to GitHub and would love to test/play with/use the application but I am not sure how to proceed after issuing the git clone https://github.com/sloan58/twilio-autodialer.git command which does complete successfully.

Would someone be able to help with what steps I need to run after running the above command to ensure I have a working instance?

Thanks for your help,
epcdrs

**Comment by sloan58** [comment]
Hi, thanks for your interest in the project!  I have some instructions for a local installation.  I'll update the readme in a bit with that info.

**Comment by epcdrs** [comment]
Thank you so much, looking forward to seeing it and being able to get a local instance running!

**Comment by sloan58** [comment]
Well, I guess "in a bit" is a relative term after all...  Sorry for the delay but the readme was updated with instructions on installing this locally.  Let me know if you have any issues or need help along the way.
