### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by Boffice** [sloan58/twilio-autodialer#17]
Hello, i am getting bellow error when i try to make a call:

**PHP: v7.2**

`count(): Parameter must be an array or an object that implements Countable
`--

`at HandleExceptions->handleError(2, 'count(): Parameter must be an array or an object that implements Countable', 'C:\\laragon\\www\\auto\\app\\Services\\PlaceTwilioCallService.php', 54, array('cdr' => object(Cdr), 'argCount' => 4))`

I have tried to make an array:
`if (count(array($argCount != 4))) `

Error: 

`Incorrect format for call request. Expected 4 parameters and got 4
`--

**Comment by anderellis** [comment]
I'm running into the exact same problem. I couldn't find anything in the read me etc. Did you have any luck @Boffice  finding a solution?

**Comment by sloan58** [comment]
Hey, thanks for the heads up.  I'm not sure how that bug snuck in there but I just pushed an update.  Check it out and let me know if you have any issues afterward.

**Comment by anderellis** [comment]
This fixed it! Thanks tremendously! I'm using this for notifying patients of telehealth equipment arriving to and from patients house. Really appreciate it.

Quick question - What type of audio files are supported? I tried an MP3 unsuccessfully.

Thanks,

**Comment by sloan58** [comment]
Great!

mp3's should work (that's what I use).  Do you have your app available on the public internet?  The Twilio Twiml directs back to the audio file hosted on your Laravel app.  I use ngrok for testing in dev, if your app isn't publicly available.  It will pull the base url from the .env `APP_URL` setting.
