### ISSUE TITLE
Support for other German Number? 

### ISSUE THREAD

**Issue by developer2013** [sloan58/twilio-autodialer#2]
Hello Sloan, 

is the script able to call german numbers? cause on your demo site it's only for the US. 

Regards
Carsten

**Comment by sloan58** [comment]
Hi Carsten,

It's not currently setup to dial German numbers (only NANP) but could be modified to support any phone number.  If you have any interest in cloning the app I could help you with the updates.  Otherwise I can update the hosted app when I get some cycles.

Thanks,
Marty

**Comment by developer2013** [comment]
Hello Marty, 

that sound's good. it will be great if you can support my to modify the code. 

Thanks
Carsten

**Comment by sloan58** [comment]
I'm super late with this update, but I added support for any E164 number.
