### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Boffice** [sloan58/twilio-autodialer#20]
Hello,

I get 3 errors related to vue when i try to compile via **npm run prod** :

```
 ERROR  Failed to compile with 3 errors                                                                                          10:22:37 AM

 error  in ./~/vuetable-2/src/components/VuetablePaginationInfo.vue
 error  in ./~/vuetable-2/src/components/VuetablePagination.vue
 error  in ./~/vuetable-2/src/components/VuetablePagination.vue
```

**Comment by sloan58** [comment]
I just pushed an update for this.  Can you do a pull and try to build again?

**Comment by Boffice** [comment]
Thanks all works fine now  
DONE  Compiled successfully in 31430ms                                                                                           7:15:53 PM
