### ISSUE TITLE
Log Procesing

### ISSUE THREAD

**Issue by Boffice** [sloan58/twilio-autodialer#21]
Hello,

I get bellow error when i try to process twilio logs from autodialer/bulk/3/process

Trying to access array offset on value of type null
--
in CsvFile.php line 250
at HandleExceptions->handleError()in CsvFile.php line 250

**Comment by sloan58** [comment]
I pushed an update for this one as well if you could try it out.  I added some try/catch blocks around the csv functions.  Also, make sure that you've run `php artisan storage:link` so the public storage folder is accessible via the web.

**Comment by RD-INFO** [comment]
Hello @sloan58 
I have trying to run your project but its showing some error, can you help me?
I have attached error screenshot. PFA.

![127 0 0 1_8000_a](https://user-images.githubusercontent.com/69051824/121177673-52c35e00-c87b-11eb-883d-0a9a698511db.png)

**Comment by sloan58** [comment]
@RD-INFO I just pushed a fix for this.  In the future, please open a new issue instead of tagging on.  This was not related to the original issue.  Thanks.
