### ISSUE TITLE
PS C:\auto\twilio-autodialer-master>  php artisan:migrate Could not open input file: artisan:migrate PS C:\auto\twilio-autodialer-master>

### ISSUE THREAD

**Issue by HassanKallab** [sloan58/twilio-autodialer#3]
Please check the below error once i run the migrate command...Any advice 

PS C:\auto\twilio-autodialer-master>  php artisan:migrate
Could not open input file: artisan:migrate

**Comment by HassanKallab** [comment]
QueryException in Connection.php line 647:
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

**Comment by sloan58** [comment]
Hello.  The first issue is due to a typo in the README - thanks for bringing that to my attention.  The command should be `php artisan migrate`.

About the second issue - it'll depend on your setup.  Do you have a database service running (like MySQL) and has your project .env file been configured to point to it?

**Comment by HassanKallab** [comment]
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_C
REATE_USER' (SQL: select * from information_schema.tables where table_schema = mysql and table_name = migrations)



[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_C
REATE_USER'

**Comment by HassanKallab** [comment]
MySQL error :+1:  [Illuminate\Database\QueryException]
 SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8mb4' (SQL: s
 ation_schema.tables where table_schema = mysql and table_name = migrations)



 [PDOException]
 SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8mb4'

**Comment by HassanKallab** [comment]
I have issue with MYSQL can provide me the setup requirements or steps

**Comment by sloan58** [comment]
Do you have some other Laravel projects running locally?  These seems like to baselines db integration issues that might not be related to this project.  I realize that my readme assumes some familiarity with Laravel apps.  I'm happy to help, but I'm not sure exactly where you're at in the process.  Plus I really suck at Windows :-(
